source "https://rubygems.org"

# Specify your gem's dependencies in audit_engine.gemspec.
gemspec

gem "puma"

gem "pg"

# Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
gem "rubocop-rails-omakase", require: false

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
